### ISSUE TITLE
Error in create_hf_dataset.py while using existing intent and slot mappings

### ISSUE THREAD

**Issue by gurnoor6** [alexa/massive#36]
When I use existing intent and slot mappings to create dataset using `create_hf_dataset.py`, and then try to use the dataset in my model, I get the following error:
```Traceback (most recent call last):
  File "scripts/test.py", line 131, in <module>
    main()
  File "scripts/test.py", line 111, in main
    outputs = trainer.predict(test_ds, tokenizer=tokenizer)
  File "/path/to/massive/massive/src/massive/utils/trainer.py", line 158, in predict
    output = self.evaluate(
  File "/path/to/massive/massive/src/massive/utils/trainer.py", line 112, in evaluate
    output = eval_loop(
  File "/path/to/env/lib/python3.8/site-packages/transformers/trainer.py", line 2926, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/path/to/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/path/to/env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/path/to/env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/path/to/massive/massive/src/massive/loaders/collator_ic_sf.py", line 121, in __call__
    return {k: torch.tensor(v, dtype=torch.int64) for k, v in pad_tok_inputs.items()}
  File "/path/to/massive/massive/src/massive/loaders/collator_ic_sf.py", line 121, in <dictcomp>
    return {k: torch.tensor(v, dtype=torch.int64) for k, v in pad_tok_inputs.items()}
ValueError: too many dimensions 'str'
```

This error does not occur when I create new mappings from the `create_hf_dataset.py` script itself.

**Comment by gurnoor6** [comment]
Update: created PR to fix this issue

**Comment by cperiz** [comment]
Thanks @gurnoor6. PR was merged.
